baseURL = "/"
googleAnalytics = ""
languageCode = "en-us"
pluralizeListTitles = false
title = "Azul Technology"
[params]
custom_css = []
custom_js = []
description = "Azul Technology"
favicon = "favicon.ico"
image = ""
name = "Gabriel Wilkes"
[params.banner]
buttontext = "Get Started"
subtitle = "Proven web design and e-commerce, get in touch today"
title = "Launching websites since 2007"
[params.contact]
buttonclear = "Clear"
buttonsend = "Send message"
enable = true
[[params.contact.address]]
city = "Kumagaya, Saitama 360-0014"
country = "Japan"
street = "0001-02-19T00:00:00+00:00"
title = "Address"
[[params.contact.email]]
email = "gabriel@azultech.com"
title = "Email"
[[params.contact.phone]]
phone = "+1 (714) 758-5275 (US)"
phone2 = "+81 (80) 3729-2966 (Japan)"
title = "Phone"
[params.error404]
heading = "Page couldn't be found"
text = "Please visit [this page](/)"
[params.footer]
copyright = "Azul Technology"
enable = true
[[params.footer.social]]
icon = "fa-twitter"
label = "Twitter"
url = "https://twitter.com/gabriel_wilkes"
[[params.footer.social]]
icon = "fa-facebook"
label = "Facebook"
url = "https://www.facebook.com/gabrielwilkes"
[[params.footer.social]]
icon = "fa-instagram"
label = "Instagram"
url = "https://www.instagram.com/gwilkes/"
[[params.footer.social]]
icon = "fa-github"
label = "GitHub"
url = "https://github.com/gabriel-wilkes"
[[params.footer.social]]
icon = "fa-linkedin"
label = "LinkedIn"
url = "https://www.linkedin.com/in/gabrielwilkes/"
[params.navigation]
menu = "Menu"
subtitle = "By Gabriel Wilkes"
title = "Azul Technology"
[[params.navigation.button2]]
name = "Contact"
url = "/index.html#contact"
[[params.navigation.links]]
name = "Home"
url = "/"
[[params.navigation.links]]
name = "About"
url = "/index.html#about"
[[params.navigation.links]]
name = "Portfolio"
url = "/portfolio"
[[params.navigation.links]]
name = "Blog"
url = "https://medium.com/@gabriel_wilkes"
[params.tiles]
enable = true
[[params.tiles.showcase]]
image = "gordon-graham.jpg"
subtitle = "E-commerce site for sunglasses"
title = "Gordon Graham"
url = "portfolio/gordon-graham"
[[params.tiles.showcase]]
image = "uramune.jpg"
subtitle = "Bilingual e-commerce site for silk dresses"
title = "Uramuné"
url = "portfolio/uramune"
[[params.tiles.showcase]]
image = "cedros.jpg"
subtitle = "Award winning Californian seafood in Tokyo"
title = "Cedros"
url = "portfolio/cedros"
[[params.tiles.showcase]]
image = "cabin.jpg"
subtitle = "Rustic whiskey and cocktail bar"
title = "Cabin"
url = "portfolio/cabin"
[[params.tiles.showcase]]
image = "yellowcab.jpg"
subtitle = "Ebook interactivity using JavaScript"
title = "Yellow Cab of the Universe"
url = "portfolio/yellow-cab"
[[params.tiles.showcase]]
image = "makertoolset.jpg"
subtitle = "Technology clubs and workshops"
title = "Maker Toolset"
url = "portfolio/maker-toolset"
[params.two]
buttontext = "Blog"
enable = true
paragraph = "    Azul Technology was started in 2007 by Gabriel Wilkes.\n    In the beginning Azul Technology was primarily focused on IT for small business.\n    However, those same small businesses also needed websites and Gabriel has been making websites since 1995."
paragraph2 = "    Over time, due to changing interest and technologies available,\n    web development and e-commerce became the primary focus.\n    If you would like to learn more please contact me or visit the social links at the bottom of the page.\n    Thanks for stopping by!"
title = "About"
url = "https://medium.com/@gabriel_wilkes"
